/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RegisteringNativeMethod */

#ifndef _Included_RegisteringNativeMethod
#define _Included_RegisteringNativeMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RegisteringNativeMethod
 * Method:    firstFunction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_RegisteringNativeMethod_firstFunction
  (JNIEnv *, jobject);

/*
 * Class:     RegisteringNativeMethod
 * Method:    SecondFunction
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_RegisteringNativeMethod_SecondFunction
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
