/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ObjectArray */

#ifndef _Included_ObjectArray
#define _Included_ObjectArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ObjectArray
 * Method:    initInt2DArray
 * Signature: (I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_ObjectArray_initInt2DArray
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
